# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ded5961497e88dd711ca18d5881006ade1655433dda890a39c53557da688a7ce69496d7640a0929b67f70d941aee9931adea4d6407cd635b1b25aaad8b6b1928

test:
  secret_key_base: 1f425ee2016f99ae3a4677c3111557bfcd9a04389d83f2576ed4694ea2173c0cf268410df7adbc9cf49ad04ffd9f8f9ee0d390ae392668a8f3248b52c2a2ea1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
